import * as fs from 'fs';
import * as path from 'path';

const routesCsv = fs.readFileSync(
  path.join(process.cwd(), '../data/gtfs/routes.txt'),
  'utf-8'
);

function parseCsv(csv: string): Record<string, string>[] {
  const lines = csv.trim().split('\n');
  const headers = lines[0].split(',').map(h => h.trim());
  return lines.slice(1).map(line => {
    const values = line.split(',');
    return Object.fromEntries(headers.map((h, i) => [h, (values[i] ?? '').trim()]));
  });
}

const routes = parseCsv(routesCsv);
const SUPPORTED_TYPES = new Set(['2', '3', '4']);

const entries = routes
  .filter(r => SUPPORTED_TYPES.has(r.route_type))
  .map(r => `  '${r.route_id}': { shortName: '${r.route_short_name.replace(/'/g, "\\'")}', routeType: ${r.route_type} }`)
  .join(',\n');

const output = `// AUTO-GENERATED by scripts/generateGtfsData.ts — do not edit manually
export interface RouteInfo {
  shortName: string;
  routeType: number;
}

export const routeMap: Record<string, RouteInfo> = {
${entries}
};
`;

const outDir = path.join(process.cwd(), 'src/poller');
fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, 'gtfsData.ts');
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`Written ${routes.filter(r => SUPPORTED_TYPES.has(r.route_type)).length} routes to ${outPath}`);
